---
kind: pipeline
type: docker
name: test
steps:
  - name: test
    image: golang:latest
    environment:
      GITHUB_LOGIN:
        from_secret: github_username
      GITHUB_PASSWORD:
        from_secret: github_token
    commands:
      - echo "machine github.com login $${GITHUB_LOGIN} password $${GITHUB_PASSWORD}" > /root/.netrc
      - chmod 600 /root/.netrc
      - go clean -testcache
      - go test -race ./...
    volumes:
      - name: deps
        path: /go

  - name: build
    image: golang:alpine
    commands:
      - go build -v -o out .
    volumes:
      - name: deps
        path: /go

volumes:
  - name: deps
    temp: {}

trigger:
  event:
    - pull_request

---
kind: template
load: circuit
data: 
  deploy: deploy
  create_tags:
    commands:
      - echo "Deploying version $DRONE_SEMVER"
      - echo -n "$DRONE_SEMVER,latest" > .tags
  backend_image:
    version: ${DRONE_SEMVER}
    tags:
      - '${DRONE_SEMVER}'
      - latest

trigger:
  branch:
    - main
  event:
    - pull_request
    - push