---
kind: template
load: test.yaml
data:
  commands:
    - echo "machine github.com login $${GITHUB_LOGIN} password $${GITHUB_PASSWORD}" > /root/.netrc
    - chmod 600 /root/.netrc
    - go clean -testcache
    - go test -race ./...

trigger:
  event:
    - pull_request

---
kind: template
load: circuit.yaml
data: 
  deploy: deploy
  create_tags:
    commands:
      - echo "Deploying version $DRONE_SEMVER"
      - echo -n "$DRONE_SEMVER,latest" > .tags
  backend_image:
    version: ${DRONE_SEMVER}
    tags:
      - '${DRONE_SEMVER}'
      - latest

trigger:
  branch:
    - main
  event:
    - pull_request
    - push