kind: pipeline
name: default
type: docker
steps:
- name: test
  image: golang:latest
  commands:
  - go test -race ./...
  - go build

trigger:
  branch:
    - main
  event:
    - pull_request
    - push

---
kind: pipeline
type: exec
name: shell

platform:
  os: darwin
  arch: amd64

steps:
- name: greeting
  commands:
  - echo hello world
