# production
---
kind: template
load: circuit.yaml
data:
  deploy: deploy
  create_tags:
    commands:
      - echo "Deploying version $DRONE_SEMVER"
      - echo -n "$DRONE_SEMVER,latest" > .tags
  backend_image:
    version: ${DRONE_SEMVER}
    tags:
      - '${DRONE_SEMVER}'
      - latest